server_name: 192.168.255.10

site_name: xlsform
site_home: '/home/ubuntu/{{ site_name }}'

virtualenv_name: xlsform_env
virtualenv_home: '{{ site_home }}/{{ virtualenv_name }}'

source_name: xlsform_src
source_home: '{{ site_home }}/{{ source_name }}'

project_name: xlsform_prj
project_home: '{{source_home}}/{{ project_name }}'

django_env: '{{ site_home }}/environment'
django_tmp_home: '/tmp/{{ site_name }}'
django_secret_key: '0'
