
- name: install packages
  apt: 
    pkg: '{{ item }}'
  with_items:
    - default-jdk-headless

- name: check django project
  stat:
    path: '{{ project_home }}'
  register: ph

- name: create project
  git:
    repo: https://github.com/opendatakit/xlsform-django.git
    dest: '{{ source_home }}'
    force: yes
    recursive: yes
    update: yes

- name: install python dependencies
  command: '{{ virtualenv_home }}/bin/pip install -r {{ source_home }}/requirements.txt'

- name: template gunicorn
  template: 
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service

- name: template xlsform
  template: 
    src: xlsform.j2
    dest: '/etc/nginx/sites-available/{{ site_name }}'

- name: create nginx link
  file:
    src: '/etc/nginx/sites-available/{{ site_name }}'
    dest: '/etc/nginx/sites-enabled/{{ site_name }}'
    state: link

- name: fix permissions
  file:
    path: '{{ site_home }}'
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: set environment
  copy: 
    content: 'DJANGO_SECRET_KEY={{ django_secret_key }}'
    dest: '{{ site_home }}/environment'

- name: run migrations
  command: '{{ virtualenv_home }}/bin/python {{ source_home }}/manage.py migrate'

- name: run collectstatic
  command: '{{ virtualenv_home }}/bin/python {{ source_home }}/manage.py collectstatic --noinput'

- name: enable and restart gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: enable and restart nginx
  service: 
    name: nginx 
    enabled: yes
    state: restarted 
