
- name: install packages
  apt: 
    pkg: '{{ item }}'
  with_items:
    - python3-dev
    - python3-pip

- name: install python packages
  pip:
    name: '{{ item }}'
    extra_args: --upgrade
    executable: pip3
  with_items:
    - pip
    - virtualenv

- name: create site home folder
  file:
    path: '{{site_home }}'
    state: directory

- name: install python env packages
  pip:
    name: '{{ item }}'
    virtualenv: '{{ virtualenv_home }}'
    virtualenv_python: python3
  with_items:
    - gunicorn
